# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 14 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "diffusioncma" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/Olllom/diffusioncma/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 932fc5a9693e5526b8b3b80b64a056f37680fe4dd68eecfe1123a1c4092fb9e4

build:
  # Uncomment the following line if the package is pure Python and the recipe is exactly the same for all platforms.
  # It is okay if the dependencies are not built for all platforms/versions, although selectors are still not allowed.
  # See https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python for more details.
  # noarch: python
  number: 0
  # If the installation is complex, or different between Unix and Windows, use separate bld.bat and build.sh files instead of this key.
  # By default, the package will be built for the Python versions supported by conda-forge and for all major OSs.
  # Add the line "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or "skip: True  # [not win]" to limit to Windows.
  # skip: True  # [py<35]
  # script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.12.1 
    - git
      #    - autoconf # [not osx]
      #    - automake # [not osx]
      #    - libtool # [not osx]

  host:
    - python {{ python }}
    - eigen
    - pybind11
    - numpy
      #    - boost # [not osx]
      #    - libcmaes # [osx]
    - libcmaes

  run:
    - python
    - pytest
    - pytest-runner
    - Click >=6.0
    - six
    - scipy
    - numpy
    - matplotlib
      # - boost # [not osx]
      # - libcmaes # [osx]
    - libcmaes


test:
  imports:
    - pydiffusioncma
    - dcma
  requires:
    - pytest
  commands:
    - pytest --pyargs dcma.testsuite

about:
  home: https://gitlab.com/Olllom/diffusioncma
  license: LGPL3
  # The license_family, i.e. "BSD" if license is "BSD-3-Clause". (optional)
  license_family: LGPL
  license_file: LICENSE
  summary: 'Maximum-likelihood estimation to calculate diffusion and free energy profiles from molecular simulations.'

  # The remaining entries in this section are optional, but recommended.
  description: Maximum-likelihood estimation to calculate diffusion and free energy profiles from molecular simulations.
  doc_url: https://gitlab.com/Olllom/diffusioncma 
  dev_url: https://gitlab.com/Olllom/diffusioncma

extra:
  recipe-maintainers:
    - Olllom

