{% set name = "diffusioncma" %}
{% set version = "0.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/Olllom/diffusioncma/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba9bb31345bfcfc622a4caa675fb2e9d2c3db0c783beb0f1afd877ef2cf02c00

build:
  number: 0
  skip: True  # [win or py<35]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.12.1 
    - git
    - libgomp  # [not osx]
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - llvm-openmp  # [osx]

  host:
    - python
    - eigen
    - pybind11
    - numpy
    - boost  # [unix]
    - setuptools

  run:
    - python
    - Click >=6.0
    - numpy 

test:
  imports:
    - pydiffusioncma
    - dcma
  requires:
    - pytest
    - pytest-runner
  commands:
    - pytest --pyargs dcma.testsuite

about:
  home: https://gitlab.com/Olllom/diffusioncma
  license: LGPL-3.0-only
  # The license_family, i.e. "BSD" if license is "BSD-3-Clause". (optional)
  license_family: LGPL
  license_file: LICENSE
  summary: 'Maximum-likelihood estimation to calculate diffusion and free energy profiles from molecular simulations.'
  description: Maximum-likelihood estimation to calculate diffusion and free energy profiles from molecular simulations.
  doc_url: https://gitlab.com/Olllom/diffusioncma 
  dev_url: https://gitlab.com/Olllom/diffusioncma

extra:
  recipe-maintainers:
    - Olllom
